"""upd table purschases

Revision ID: 5ca0f991801d
Revises: 1720ca777755
Create Date: 2024-12-26 13:28:44.493520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca0f991801d'
down_revision: Union[str, None] = '1720ca777755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_type', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'purchases', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='unique')
    op.drop_column('purchases', 'payment_type')
    # ### end Alembic commands ###
