-- u782528968_Erx8s.wxrq_product definition

CREATE TABLE `wxrq_product` (
  `id_product` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_supplier` int(10) unsigned DEFAULT NULL,
  `id_manufacturer` int(10) unsigned DEFAULT NULL,
  `id_category_default` int(10) unsigned DEFAULT NULL,
  `id_shop_default` int(10) unsigned NOT NULL DEFAULT 1,
  `id_tax_rules_group` int(11) unsigned NOT NULL,
  `on_sale` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT 'Распродажа (1/0)',
  `online_only` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `ean13` varchar(13) DEFAULT NULL,
  `isbn` varchar(32) DEFAULT NULL,
  `upc` varchar(12) DEFAULT NULL,
  `mpn` varchar(40) DEFAULT NULL,
  `ecotax` decimal(17,6) NOT NULL DEFAULT 0.000000,
  `quantity` int(10) NOT NULL DEFAULT 0,
  `minimal_quantity` int(10) unsigned NOT NULL DEFAULT 1,
  `low_stock_threshold` int(10) DEFAULT NULL,
  `low_stock_alert` tinyint(1) NOT NULL DEFAULT 0,
  `price` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `wholesale_price` decimal(20,6) NOT NULL DEFAULT 0.000000 COMMENT 'это относится к ценам для оптовых покупателей.',
  `unity` varchar(255) DEFAULT NULL,
  `unit_price_ratio` decimal(20,6) NOT NULL DEFAULT 0.000000 COMMENT 'В PrestaShop, поле unit_price_ratio в таблице ps_product представляет собой коэффициент, используемый для расчета цены продукта на основе его базовой цены (цены за единицу) и выбранной единицы продажи.\r\n\r\nНапример, если базовая цена продукта указана за килограмм, а единица продажи выбрана как грамм, то unit_price_ratio будет представлять соотношение между килограммом и граммом (обычно 1000 для данного примера). Таким образом, чтобы рассчитать цену продукта в граммах, базовая цена будет умножена на unit_price_ratio, чтобы получить цену за грамм.\r\n\r\nЭто поле позволяет адаптировать цены продуктов к различным единицам измерения без необходимости изменения базовой цены.',
  `additional_shipping_cost` decimal(20,6) NOT NULL DEFAULT 0.000000 COMMENT 'стоимость доставки',
  `reference` varchar(64) DEFAULT NULL,
  `supplier_reference` varchar(64) DEFAULT NULL,
  `location` varchar(255) NOT NULL DEFAULT '',
  `width` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `weight` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `height` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `depth` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `volume` varchar(100) DEFAULT NULL,
  `out_of_stock` int(10) unsigned NOT NULL DEFAULT 2 COMMENT 'В PrestaShop 1.7 поле ps_product.out_of_stock в базе данных означает, находится ли товар в настоящее время вне запаса (out of stock). Это поле принимает значение 1, если товар закончился на складе, и 0, если товар все еще доступен для продажи.\r\n\r\nТип данных int(10) unsigned указывает на то, что это поле представляет собой целое число (integer) без знака (unsigned), которое может хранить значения от 0 до 4294967295 (включительно). Такой тип данных часто используется для флагов или булевых значений, когда необходимо хранить всего два возможных состояния.\r\n\r\nВ контексте PrestaShop, когда товар заканчивается на складе и out_of_stock установлено в 1, это может влиять на отображение товара на сайте. Например, магазин может скрывать товары, которые временно отсутствуют в наличии, чтобы избежать недоразумений у покупателей.',
  `additional_delivery_times` tinyint(1) unsigned NOT NULL DEFAULT 1 COMMENT 'дополнительные сроки доставки',
  `quantity_discount` tinyint(1) DEFAULT 0,
  `customizable` tinyint(2) NOT NULL DEFAULT 0,
  `uploadable_files` tinyint(4) NOT NULL DEFAULT 0,
  `text_fields` tinyint(4) NOT NULL DEFAULT 0,
  `active` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `redirect_type` enum('404','301-product','302-product','301-category','302-category') NOT NULL DEFAULT '404',
  `id_type_redirected` int(10) unsigned NOT NULL DEFAULT 0,
  `available_for_order` tinyint(1) NOT NULL DEFAULT 1,
  `available_date` date DEFAULT NULL,
  `show_condition` tinyint(1) NOT NULL DEFAULT 0,
  `condition` enum('new','used','refurbished') NOT NULL DEFAULT 'new',
  `show_price` tinyint(1) NOT NULL DEFAULT 1,
  `indexed` tinyint(1) NOT NULL DEFAULT 0,
  `visibility` enum('both','catalog','search','none') NOT NULL DEFAULT 'both',
  `cache_is_pack` tinyint(1) NOT NULL DEFAULT 0,
  `cache_has_attachments` tinyint(1) NOT NULL DEFAULT 0,
  `is_virtual` tinyint(1) NOT NULL DEFAULT 0,
  `cache_default_attribute` int(10) unsigned DEFAULT NULL,
  `date_add` datetime NOT NULL,
  `date_upd` datetime NOT NULL,
  `advanced_stock_management` tinyint(1) NOT NULL DEFAULT 0,
  `pack_stock_type` int(11) unsigned NOT NULL DEFAULT 3,
  `state` int(11) unsigned NOT NULL DEFAULT 1 COMMENT 'Posted May 6, 2019\r\n  On 3/5/2019 at 5:26 AM, lifeform said:\r\ni found in sql filter in product list prestashop that "state = 1" what it used for?\r\n\r\nState = 0 -> means Temporary\r\nState = 1 -> means Saved\r\n\r\nhttps://github.com/prestaShop/PrestaShop/blob/develop/classes/Product.php#L313\r\nWhen we hit "Add new product" PS creates a new record on DB (table product) with State = 0 (Temporary) and when we finally hit "Save" it change State to 1 (Saved).\r\n\r\nState = 0 -> means Temporary\r\nState = 1 -> means Saved\r\n\r\nhttps://github.com/prestaShop/PrestaShop/blob/develop/classes/Product.php#L313\r\n\r\nWhen we hit "Add new product" PS creates a new record on DB (table product) with State = 0 (Temporary) and when we finally hit "Save" it change State to 1 (Saved).',
  `product_type` enum('standard','pack','virtual','combinations','product_as_service','') NOT NULL DEFAULT '',
  `product_as_service` tinyint(1) DEFAULT NULL,
  `link_to_video` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id_product`),
  KEY `reference_idx` (`reference`),
  KEY `supplier_reference_idx` (`supplier_reference`),
  KEY `product_supplier` (`id_supplier`),
  KEY `product_manufacturer` (`id_manufacturer`,`id_product`),
  KEY `id_category_default` (`id_category_default`),
  KEY `indexed` (`indexed`),
  KEY `date_add` (`date_add`),
  KEY `state` (`state`,`date_upd`)
) ENGINE=InnoDB AUTO_INCREMENT=2661 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;