-- u782528968_Erx8s.wxrq_product_lang definition

CREATE TABLE `wxrq_product_lang` (
  `id_product` int(10) unsigned NOT NULL,
  `id_shop` int(11) unsigned NOT NULL DEFAULT 1,
  `id_lang` int(10) unsigned NOT NULL,
  `name` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` text DEFAULT NULL,
  `description_short` text DEFAULT NULL,
  `ingredients` tinytext DEFAULT NULL,
  `how_to_use` tinytext DEFAULT NULL COMMENT 'нструкция по использованию товара',
  `specification` tinytext DEFAULT NULL,
  `meta_description` varchar(512) DEFAULT NULL,
  `meta_keywords` varchar(256) DEFAULT NULL,
  `meta_title` varchar(256) DEFAULT NULL,
  `link_rewrite` varchar(128) NOT NULL,
  `available_now` varchar(256) DEFAULT NULL,
  `available_later` varchar(256) DEFAULT NULL,
  `delivery_in_stock` varchar(256) DEFAULT NULL COMMENT '(Доставка при наличии товара): Текст, который будет отображаться, когда товар есть в наличии.',
  `delivery_out_stock` varchar(256) DEFAULT NULL COMMENT '(Доставка если товара нет в наличии): Текст, который будет отображаться, когда товара нет в наличии.',
  `delivery_additional_message` varchar(256) DEFAULT NULL COMMENT 'Дополнительное сообщение к условиям отправки',
  `affiliate_short_link` varchar(256) DEFAULT NULL,
  `affiliate_text` mediumtext DEFAULT NULL,
  `affiliate_summary` mediumtext DEFAULT NULL,
  `affiliate_summary_2` mediumtext DEFAULT NULL,
  `affiliate_image_small` varchar(512) DEFAULT NULL,
  `affiliate_image_medium` varchar(512) DEFAULT NULL,
  `affiliate_image_large` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id_product`,`id_shop`,`id_lang`),
  KEY `id_lang` (`id_lang`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;